title:  "blog"
tagline: "what andrea dreamed up today"

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

menu:
- {name: 'Interesting Facts', folder: 'pages', file: 'facts.html'}
- {name: 'Learning Resources', folder: 'pages', file: 'resources.html'}
- {name: 'Sample Posts', folder: 'pages', file: 'sample-posts.html'}
- {name: 'Documentation', folder: 'pages', file: 'documentation.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/AndreaC95102027'}
- {icon: 'facebook', link: 'https://www.facebook.com/andrea.chamorro.1428'}
- {icon: 'instagram', link: 'https://instagram.com/obviously_andrea/'}
- {icon: 'envelope', link: 'mailto:andrea.colleges@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
